version: "3.8"

services:
  telegram-bot:
    build: .
    container_name: telegram_summary_bot
    restart: always
    env_file:
      - secret.env
    volumes:
      - ./group_members.json:/app/group_members.json

volumes: {}

networks: {}
