version: "3.8"

services:
  telegram-bot:
    build: .
    container_name: telegram_summary_bot
    restart: always
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      GROUP_CHAT_ID: "${GROUP_CHAT_ID}"
    volumes:
      - ./group_members.json:/app/group_members.json

volumes: {}

networks: {}
