version: "3.8"
services:
  telegram-bot:
    build: .
    container_name: telegram_summary_bot
    restart: always
    env_file:
      - secret.env
    environment:
      OLLAMA_API_URL: http://ollama:11434/api/generate
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
volumes:
  ollama_data: {} 